= Prefam
:source-highlighter: rouge

Preloaded file access monitor.

_Prefam_ is a small and fast library that overrides system calls `open*`, `exec*`, `posix_spawn*` and records which file paths have been accessed by these system calls.

While it is not as robust as using `fanotify` or other kernel-level instrumentation, for example eBPF, it can be easily hooked onto programs from user space.

== Usage

In order to use this library you need to preload it and pass it the output file descriptor number via an environment variable `PREFAM_OUTPUT_FD`.

The library writes accessed file paths into the provided file descriptor as soon as the events happen.
The format of the output is a line-separated list of file paths.

.Example usage from shell:
[source,bash]
----
exec 3>output.log

PREFAM_OUTPUT_FD=3 LD_PRELOAD=${libdir}/libprefam.so.1 command [args...]

exec 3>&-
----

== Building

Build the project:

----
$ make compile
----

Build manual page:

----
$ make manpage
----

Run tests:

----
$ make test
----

Generate coverage report:

----
$ make coverage
----
