#!/bin/bash

set -e

function usage
{
	echo "\
Usage: ${0##*/} [-a] [-d file_descriptor] <file> <command> [args...]
    -a      Append to the file instead of creating it
    -d FD   Explicit file descriptor number to use, if not provided, will be generated automatically" >&2
	exit 1
}

append=0

while getopts "ad:" opt; do
	case "${opt}" in
		a) append=1 ;;
		d) fd="${OPTARG}" ;;
		*) usage ;;
	esac
done
shift $((OPTIND - 1))

if [ $# -lt 2 ]; then
	usage
fi

file="${1}"
shift

if [ "${append}" -eq 1 ]; then
	exec {fd}>>"${file}"
else
	exec {fd}>"${file}"
fi

PREFAM_OUTPUT_FD="${fd}" LD_PRELOAD="libprefam.so.1" exec "$@"
