#!/bin/bash

set -e

function usage
{
	echo "Usage: ${0##*/} <file> <command> [args...]" >&2
	exit 1
}

if [ $# -lt 2 ]; then
	usage
fi

file="${1}"
shift

PREFAM_OUTPUT_PATH="${file}" LD_PRELOAD="libprefam.so.1" exec "$@"
