= prefam(3)
:doctype: manpage
:backend: manpage
:mansource: PREFAM
:manmanual: Prefam Manual

== NAME
prefam - preloaded file access monitor

== SYNOPSIS
*PREFAM_OUTPUT_FD*=_fd_ *LD_PRELOAD*=libprefam.so.1 *command* [args...]

== DESCRIPTION
_Prefam_ is a library that interposes C library functions of families *open*, *fopen*, *opendir*, *exec* and *posix_spawn* and records which file paths have been accessed by these system calls.

The library writes accessed file paths into the provided file descriptor as soon as the events happen.
The accessed file paths written to the output are separated by newlines.

Warning and error messages are printed on the standard error output.

=== Preloaded functions
_open_ - *open*, *open64*, *openat*, *openat64* +
_fopen_ - *fopen*, *fopen64*, *freopen*, *freopen64* +
_opendir_ - *opendir*, *fdopendir* +
_exec_ - *execve*, *fexecve*, *execv*, *execle*, *execl*, *execvp*, *execlp*, *execvpe* +
_posix_spawn_ - *posix_spawn*, *posix_spawnp* +

== EXIT STATUS
In case of a fatal error the library exits the whole program with *127*.

== ENVIRONMENT VARIABLES
*PREFAM_OUTPUT_FD*:: The numeric file descriptor into which the library writes the accessed paths.

== EXAMPLES
.Example usage from shell
[subs="+quotes"]
----
exec {fd}>output.log
*PREFAM_OUTPUT_FD*={fd} *LD_PRELOAD*=libprefam.so.1 *command* _[args...]_
exec {fd}>&-
----

== SEE ALSO
*prefam*(1)

== REPORTING BUGS
Bugs should be reported through the issue tracker at Github: https://github.com/mkoncek/prefam/issues.

== AUTHOR
Written by Marián Konček.

== COPYRIGHT
Copyright (C) 2026 Red Hat, Inc.
Licensed under the Apache License, Version 2.0.
