name: Continuous Integration
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - version: 8
            container: registry.access.redhat.com/ubi8
            ldlibs: "-ldl"
          - version: 9
            container: registry.access.redhat.com/ubi9
            ldlibs: ""
          - version: 10
            container: registry.access.redhat.com/ubi10
            ldlibs: ""
    container: ${{ matrix.container }}
    env:
      LDLIBS: ${{ matrix.ldlibs }}
    steps:
      - name: Checkout git repository
        uses: actions/checkout@v7
      - name: Install dependencies
        run: |
          dnf -y install https://dl.fedoraproject.org/pub/epel/epel-release-latest-${{ matrix.version }}.noarch.rpm
          dnf -y install gcc make asciidoctor
      - name: Build manpages
        run: |
          make -j$(nproc) manpages
      - name: Compile
        run: |
          make -j$(nproc) test-compile
      - name: Test
        run: |
          make test
